### ISSUE TITLE
Allow to use rustfmt-nightly

### ISSUE THREAD

**Issue by Phaiax** [Mitranim/sublime-rust-fmt#2]
It would be cool if I could write

```
// RustFmt Settings - User
{
    "executable": "rustup run nightly rustfmt"
}
```

That would allow me to use `rustfmt-nightly` on stable projects.

Thanks, Daniel

**Comment by mitranim** [comment]
Pushed new version: https://github.com/Mitranim/sublime-rust-fmt/releases/tag/0.1.3

The `executable` setting now accepts either a string (as before) or a list of
command line arguments:

```sublime-settings
  "executable": ["rustup", "run", "nightly", "rustfmt"]
```

Let me know how it works.

(Note: it takes Package Control 1-2 hours to notice a new release)

**Comment by Phaiax** [comment]
It works, thanks a lot. That was fast. :+1:
