### ISSUE TITLE
Use correct rustfmt.toml by traversing up the directory tree

### ISSUE THREAD

**Issue by LukasKalbertodt** [Mitranim/sublime-rust-fmt#3]
When formatting buffers corresponding to a file on disk, it would be nice to get the same behavior as when executing `rustfmt` from the command line: it searches for a `rustfmt.toml` starting at the directory of the file and going up from there. As far as I can see, this plugin does not search for a `rustfmt.toml` at the moment..

**Comment by mitranim** [comment]
Thanks for raising the issue.

Should be fairly easy to support by passing the current directory to `rustfmt` as `--config-path` and letting it find the config by itself. Unfortunately, the feature only works in `rustfmt-nightly`, which fails to run on my system. Fairly safe to assume that many others use the regular `rustfmt`. Should probably wait until it stabilizes.

**Comment by LukasKalbertodt** [comment]
Oh, I see. I do use the nighlty version via `"executable": ["rustup", "run", "nightly", "rustfmt"]`. Maybe we could add a flag `unstableFeatures` in the settings to enable things like this? I don't expect rustfmt to stabilize anytime soon tbh :/

Apart from that: I'm fairly sure even the old (stable) `rustfmt` was configurable via `rustfmt.toml` and that it would also traverse all parents directories until a configuration file is found. Maybe this plugin could start `rustfmt` in the directory of the file being formatted(*)? Shouldn't that work?

(*) Or maybe: path of sublime project if a project is opened, otherwise path of file being formatted.

**Comment by mitranim** [comment]
There's actually a fresh [pull request](pull/5) for that. Until it's merged, you could pull from [csmulhern/sublime-rust-fmt](https://github.com/csmulhern/sublime-rust-fmt) and see if it works for you, or suggest changes if not.

**Comment by mitranim** [comment]
Released `0.1.5` with support for config files. Let me know if it works for you.

**Comment by LukasKalbertodt** [comment]
Works for me :)

Thank you and @csmulhern for solving my issues with this plugin so quickly!
