### ISSUE TITLE
Use project-specific settings?

### ISSUE THREAD

**Issue by LukasKalbertodt** [Mitranim/sublime-rust-fmt#4]
Hi there!

I tried to adjust some settings for one of my projects, but it doesn't seem to work. For example, I used this project config:

```json
{
    "folders":
    [
        {
            "path": "."
        }
    ],
    "settings":
    {
        "format_on_save": false,
    }
}
```

It has no effect.. I also couldn't find another way of specifying it for this project only...

**Comment by mitranim** [comment]
Hi there, glad you're finding the plugin useful. Just pushed `0.1.4` that also looks for settings in a `"RustFmt"` dict in Sublime settings. Let me know if it works for you.

**Comment by LukasKalbertodt** [comment]
Works for me! Thank you a lot :)
