### ISSUE TITLE
Does not work with latest rustfmt

### ISSUE THREAD

**Issue by ehuss** [Mitranim/sublime-rust-fmt#6]
Unfortunately this plugin no longer works with `rustfmt` starting with nightly 2018-05-16 (or thereabouts).  The `--write-mode display` option has been renamed to `--emit stdout`.  See https://github.com/rust-lang-nursery/rustfmt/commit/5d9f5aa05a668e7dfef87b46d89dad2884df9d41

**Comment by mitranim** [comment]
Thanks for the notice. Released an update that should fix this.

**Comment by mitranim** [comment]
Assuming it works.
