### ISSUE TITLE
Converts tabs to spaces?

### ISSUE THREAD

**Issue by soumya92** [Mitranim/sublime-rust-fmt#9]
Despite "hard_tabs = true" in rustfmt.toml, it seems the plugin forces spaces. Any chance you could detect the option from the config, or avoid changing the view settings on format?

**Comment by mitranim** [comment]
This was intended as a convenience feature for automatically translating "improper" tab indentation into "proper" space indentation. Apologies for the inconvenience. Just pushed `0.1.8` that no longer forces spaces.

**Comment by soumya92** [comment]
That works perfectly! Thanks for the quick response :+1:
